version: "3.12"

services:
  db:
    image: postgres
    container_name: my_posgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
